### ISSUE TITLE
Download URL changed since version 2

### ISSUE THREAD

**Issue by bcroq** [virtualstaticvoid/asdf-docker-compose#2]
When installing docker-compose 2.0.1 using `asdf install docker-compose 2.0.1` the download fails and `~/.asdf/installs/docker-compose/2.0.1/bin/docker-compose` contains "Not found".

In fact, the download URL has changed :
- v1.29.2 : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
- v2.0.1 : https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-x86_64

**Comment by virtualstaticvoid** [comment]
Hi @bcroq 

Thanks for the issue report.

It turns out that `docker-compose` has been rewritten since version 2 and is now installed as a docker CLI plugin instead on Linux and part of Docker Desktop on Mac.

> `docker-compose` has been completely rewriten from scratch in Golang (V1 was in Python).
> The installation instructions for Compose V2 differ from V1.
> V2 is not a standalone binary anymore and installation scripts will have to be adjusted.

See the [About update and backward compatibility][update] and [Where to get Docker Compose][install]
pages of the `docker-compose` repository for further details.

I will update this plugin to include this on the README and show a warning when running `asdf list-all docker-compose` or when a user attempts to install a version >= 2.0.

[install]: https://github.com/docker/compose#where-to-get-docker-compose
[update]: https://github.com/docker/compose#about-update-and-backward-compatibility
